### ISSUE TITLE
api树上和自动拼接的请求路径多了个路径符“/”

### ISSUE THREAD

**Issue by xufanchn** [15815162480/http#3]
环境：
* Idea 2023.2.3
* ApiTool 1.4.4

现象：
* api树上接口最后的部分前缀多了个“/”
* 自动拼接的请求路径也多了个“/”

![image](https://github.com/15815162480/http/assets/49760248/50c54b3f-f697-4c64-8d89-960c2d9c6c7b)
![image](https://github.com/15815162480/http/assets/49760248/6bb0dda4-03ad-42a4-87e0-1adce52f05a1)

**Comment by 15815162480** [comment]
没考虑到 Controller 上请求路径为空，将会在下个版本修复
