### ISSUE TITLE
Plugin can't show all the api request list, please fix it!!

### ISSUE THREAD

**Issue by kitare17** [15815162480/http#4]
Plugin can't show all the api request list, please fix it!!
![image](https://github.com/15815162480/http/assets/104090949/afafc38c-7e36-4526-9c1a-6aa6d2923c5b)

**Comment by 1104340845** [comment]
Has it not been displayed even after refreshing?
![image](https://github.com/15815162480/http/assets/74954382/a7aebb1a-83d8-4f39-b0b6-094d8ff49265)
Is there any filtering?

**Comment by 15815162480** [comment]
Has it not been displayed even after refreshing?
![image](https://github.com/15815162480/http/assets/74909494/f4bfef82-06c1-4a1a-a80d-0c698a92e772)
Is there any filtering?

**Comment by kitare17** [comment]
![image](https://github.com/15815162480/http/assets/104090949/e36b31fd-8c51-43c9-abcc-e3b7569db50b)
![image](https://github.com/15815162480/http/assets/104090949/fede27e9-ed2b-46ea-af62-53687fd9db7a)

I select all of them and try to refresh. I work file(MultipartFile class) with api. Can you try to code with MultipartFile class?
I think it cause this bug.
Thank!!

**Comment by kitare17** [comment]
Hi bro, after try to fix and I create clone project and it is fixed!
Hope you have a nice day!
Thanks for your attention!
